-- Django (5.2) schema of the portal DB, generated with `pg_dump -s` from a database built by the REAL
-- Django migrations (django_scratch, see /home/claude/briefs/agent6/reset_and_populate.sh).
-- Foreign-key constraints and the single-PENDING partial unique index are intentionally REMOVED so tests can
-- create a "legacy database with lost integrity" (orphans, several PENDING schedules) without superuser rights.
SET client_encoding = 'UTF8';


SET statement_timeout = 0;

CREATE TABLE public.accounts_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    email character varying(254) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    phone character varying(20),
    role character varying(20) NOT NULL,
    is_active boolean NOT NULL,
    is_staff boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    phone_verified_at timestamp with time zone
);

CREATE TABLE public.accounts_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);

ALTER TABLE public.accounts_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.accounts_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.accounts_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);

ALTER TABLE public.accounts_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.advertisements_advertisement (
    id bigint NOT NULL,
    name character varying(150) NOT NULL,
    placement character varying(20) NOT NULL,
    creative_type character varying(20) NOT NULL,
    image_url character varying(500) NOT NULL,
    bunny_storage_path character varying(500) NOT NULL,
    target_url character varying(500) NOT NULL,
    start_at timestamp with time zone NOT NULL,
    end_at timestamp with time zone NOT NULL,
    is_active boolean NOT NULL,
    priority integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT advertisements_advertisement_priority_check CHECK ((priority >= 0))
);

ALTER TABLE public.advertisements_advertisement ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.advertisements_advertisement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.ai_aianalysisresult (
    id bigint NOT NULL,
    provider character varying(20) NOT NULL,
    model_name character varying(100) NOT NULL,
    status character varying(20) NOT NULL,
    error_message text NOT NULL,
    readability_score double precision,
    grammar_issues jsonb NOT NULL,
    seo_suggestions jsonb NOT NULL,
    ai_content_likelihood double precision,
    ai_content_rationale text NOT NULL,
    raw_response jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    article_id bigint NOT NULL,
    requested_by_id bigint
);

ALTER TABLE public.ai_aianalysisresult ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ai_aianalysisresult_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.ai_plagiarismcheckresult (
    id bigint NOT NULL,
    provider character varying(20) NOT NULL,
    scan_id character varying(100) NOT NULL,
    status character varying(20) NOT NULL,
    error_message text NOT NULL,
    similarity_score double precision,
    matches jsonb NOT NULL,
    raw_response jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    completed_at timestamp with time zone,
    article_id bigint NOT NULL,
    requested_by_id bigint
);

ALTER TABLE public.ai_plagiarismcheckresult ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ai_plagiarismcheckresult_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.analytics_articledailyview (
    id bigint NOT NULL,
    date date NOT NULL,
    views integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    article_id bigint NOT NULL,
    CONSTRAINT analytics_articledailyview_views_check CHECK ((views >= 0))
);

ALTER TABLE public.analytics_articledailyview ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.analytics_articledailyview_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.articles_article (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    slug character varying(280) NOT NULL,
    excerpt text NOT NULL,
    content text NOT NULL,
    status character varying(20) NOT NULL,
    rejection_reason text NOT NULL,
    access_level character varying(20) NOT NULL,
    scheduled_publish_at timestamp with time zone,
    published_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    author_id bigint NOT NULL,
    category_id bigint,
    search_vector tsvector,
    subscribers_notified_at timestamp with time zone,
    subcategory_id bigint,
    assigned_reporter_id bigint,
    faqs jsonb NOT NULL,
    location_name character varying(200) NOT NULL
);

ALTER TABLE public.articles_article ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.articles_article_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.articles_article_tags (
    id bigint NOT NULL,
    article_id bigint NOT NULL,
    tag_id bigint NOT NULL
);

ALTER TABLE public.articles_article_tags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.articles_article_tags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.categories_category (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    slug character varying(120) NOT NULL,
    description text NOT NULL,
    image_url character varying(200),
    image_storage_path character varying(255),
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    industry_id bigint
);

ALTER TABLE public.categories_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.categories_industry (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    slug character varying(120) NOT NULL,
    description text NOT NULL,
    is_active boolean NOT NULL,
    display_order integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT categories_industry_display_order_check CHECK ((display_order >= 0))
);

ALTER TABLE public.categories_industry ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_industry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.categories_subcategory (
    id bigint NOT NULL,
    name character varying(150) NOT NULL,
    slug character varying(170) NOT NULL,
    description text NOT NULL,
    is_active boolean NOT NULL,
    display_order integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    category_id bigint NOT NULL,
    CONSTRAINT categories_subcategory_display_order_check CHECK ((display_order >= 0))
);

ALTER TABLE public.categories_subcategory ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_subcategory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.categories_tag (
    id bigint NOT NULL,
    name character varying(60) NOT NULL,
    slug character varying(80) NOT NULL,
    created_at timestamp with time zone NOT NULL
);

ALTER TABLE public.categories_tag ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);

CREATE TABLE public.media_articleimage (
    id bigint NOT NULL,
    bunny_url character varying(500) NOT NULL,
    bunny_storage_path character varying(500) NOT NULL,
    alt_text character varying(255) NOT NULL,
    caption character varying(500) NOT NULL,
    is_featured boolean NOT NULL,
    display_order integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    article_id bigint NOT NULL,
    uploaded_by_id bigint NOT NULL,
    CONSTRAINT media_articleimage_display_order_check CHECK ((display_order >= 0))
);

ALTER TABLE public.media_articleimage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.media_articleimage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.media_mediametadata (
    id bigint NOT NULL,
    original_filename character varying(255) NOT NULL,
    content_type character varying(100) NOT NULL,
    file_size_bytes integer NOT NULL,
    width integer NOT NULL,
    height integer NOT NULL,
    checksum character varying(64) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    image_id bigint NOT NULL,
    CONSTRAINT media_mediametadata_file_size_bytes_check CHECK ((file_size_bytes >= 0)),
    CONSTRAINT media_mediametadata_height_check CHECK ((height >= 0)),
    CONSTRAINT media_mediametadata_width_check CHECK ((width >= 0))
);

ALTER TABLE public.media_mediametadata ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.media_mediametadata_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.notifications_notification (
    id bigint NOT NULL,
    notification_type character varying(30) NOT NULL,
    message character varying(500) NOT NULL,
    is_read boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    article_id bigint,
    recipient_id bigint NOT NULL
);

ALTER TABLE public.notifications_notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.reporters_articlereview (
    id bigint NOT NULL,
    action character varying(20) NOT NULL,
    from_status character varying(20) NOT NULL,
    to_status character varying(20) NOT NULL,
    reason text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    article_id bigint NOT NULL,
    reviewer_id bigint
);

ALTER TABLE public.reporters_articlereview ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reporters_articlereview_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.reporters_publishingschedule (
    id bigint NOT NULL,
    scheduled_for timestamp with time zone NOT NULL,
    status character varying(20) NOT NULL,
    executed_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    article_id bigint NOT NULL,
    scheduled_by_id bigint NOT NULL
);

ALTER TABLE public.reporters_publishingschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reporters_publishingschedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.reporters_reportercategoryassignment (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    assigned_by_id bigint,
    category_id bigint NOT NULL,
    reporter_id bigint NOT NULL
);

ALTER TABLE public.reporters_reportercategoryassignment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reporters_reportercategoryassignment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.subscriptions_payment (
    id bigint NOT NULL,
    razorpay_order_id character varying(100) NOT NULL,
    razorpay_payment_id character varying(100) NOT NULL,
    razorpay_signature character varying(255) NOT NULL,
    amount numeric(10,2) NOT NULL,
    currency character varying(3) NOT NULL,
    status character varying(20) NOT NULL,
    failure_reason character varying(255) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL,
    subscription_id bigint NOT NULL
);

ALTER TABLE public.subscriptions_payment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subscriptions_payment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.subscriptions_phoneotp (
    id bigint NOT NULL,
    phone character varying(20) NOT NULL,
    code_hash character varying(255) NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    attempts smallint NOT NULL,
    is_verified boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT subscriptions_phoneotp_attempts_check CHECK ((attempts >= 0))
);

ALTER TABLE public.subscriptions_phoneotp ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subscriptions_phoneotp_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.subscriptions_subscription (
    id bigint NOT NULL,
    status character varying(20) NOT NULL,
    started_at timestamp with time zone,
    expires_at timestamp with time zone,
    expiring_notified_at timestamp with time zone,
    expired_notified_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL,
    plan_id bigint NOT NULL,
    contact_email character varying(254) NOT NULL,
    contact_phone character varying(20) NOT NULL
);

ALTER TABLE public.subscriptions_subscription ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subscriptions_subscription_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.subscriptions_subscriptionplan (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    slug character varying(120) NOT NULL,
    description text NOT NULL,
    price_amount numeric(10,2) NOT NULL,
    price_currency character varying(3) NOT NULL,
    duration_days integer NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT subscriptions_subscriptionplan_duration_days_check CHECK ((duration_days >= 0))
);

ALTER TABLE public.subscriptions_subscriptionplan ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subscriptions_subscriptionplan_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.token_blacklist_blacklistedtoken (
    id bigint NOT NULL,
    blacklisted_at timestamp with time zone NOT NULL,
    token_id bigint NOT NULL
);

ALTER TABLE public.token_blacklist_blacklistedtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_blacklistedtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.token_blacklist_outstandingtoken (
    id bigint NOT NULL,
    token text NOT NULL,
    created_at timestamp with time zone,
    expires_at timestamp with time zone NOT NULL,
    user_id bigint,
    jti character varying(255) NOT NULL
);

ALTER TABLE public.token_blacklist_outstandingtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_outstandingtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_email_key UNIQUE (email);

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_user_id_group_id_59c0b32f_uniq UNIQUE (user_id, group_id);

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_phone_key UNIQUE (phone);

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq UNIQUE (user_id, permission_id);

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_permissions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.advertisements_advertisement
    ADD CONSTRAINT advertisements_advertisement_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.ai_aianalysisresult
    ADD CONSTRAINT ai_aianalysisresult_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.ai_plagiarismcheckresult
    ADD CONSTRAINT ai_plagiarismcheckresult_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.ai_plagiarismcheckresult
    ADD CONSTRAINT ai_plagiarismcheckresult_scan_id_key UNIQUE (scan_id);

ALTER TABLE ONLY public.analytics_articledailyview
    ADD CONSTRAINT analytics_articledailyview_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.articles_article
    ADD CONSTRAINT articles_article_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.articles_article
    ADD CONSTRAINT articles_article_slug_key UNIQUE (slug);

ALTER TABLE ONLY public.articles_article_tags
    ADD CONSTRAINT articles_article_tags_article_id_tag_id_1988a91e_uniq UNIQUE (article_id, tag_id);

ALTER TABLE ONLY public.articles_article_tags
    ADD CONSTRAINT articles_article_tags_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.categories_category
    ADD CONSTRAINT categories_category_name_key UNIQUE (name);

ALTER TABLE ONLY public.categories_category
    ADD CONSTRAINT categories_category_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.categories_category
    ADD CONSTRAINT categories_category_slug_key UNIQUE (slug);

ALTER TABLE ONLY public.categories_industry
    ADD CONSTRAINT categories_industry_name_key UNIQUE (name);

ALTER TABLE ONLY public.categories_industry
    ADD CONSTRAINT categories_industry_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.categories_industry
    ADD CONSTRAINT categories_industry_slug_key UNIQUE (slug);

ALTER TABLE ONLY public.categories_subcategory
    ADD CONSTRAINT categories_subcategory_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.categories_tag
    ADD CONSTRAINT categories_tag_name_key UNIQUE (name);

ALTER TABLE ONLY public.categories_tag
    ADD CONSTRAINT categories_tag_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.categories_tag
    ADD CONSTRAINT categories_tag_slug_key UNIQUE (slug);

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);

ALTER TABLE ONLY public.media_articleimage
    ADD CONSTRAINT media_articleimage_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.media_mediametadata
    ADD CONSTRAINT media_mediametadata_image_id_key UNIQUE (image_id);

ALTER TABLE ONLY public.media_mediametadata
    ADD CONSTRAINT media_mediametadata_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.notifications_notification
    ADD CONSTRAINT notifications_notification_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.reporters_articlereview
    ADD CONSTRAINT reporters_articlereview_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.reporters_publishingschedule
    ADD CONSTRAINT reporters_publishingschedule_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.reporters_reportercategoryassignment
    ADD CONSTRAINT reporters_reportercategoryassignment_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.subscriptions_payment
    ADD CONSTRAINT subscriptions_payment_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.subscriptions_payment
    ADD CONSTRAINT subscriptions_payment_razorpay_order_id_key UNIQUE (razorpay_order_id);

ALTER TABLE ONLY public.subscriptions_phoneotp
    ADD CONSTRAINT subscriptions_phoneotp_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.subscriptions_subscription
    ADD CONSTRAINT subscriptions_subscription_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.subscriptions_subscriptionplan
    ADD CONSTRAINT subscriptions_subscriptionplan_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.subscriptions_subscriptionplan
    ADD CONSTRAINT subscriptions_subscriptionplan_slug_key UNIQUE (slug);

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_key UNIQUE (token_id);

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq UNIQUE (jti);

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.analytics_articledailyview
    ADD CONSTRAINT uniq_article_daily_view UNIQUE (article_id, date);

ALTER TABLE ONLY public.reporters_reportercategoryassignment
    ADD CONSTRAINT uniq_reporter_category_assignment UNIQUE (reporter_id, category_id);

ALTER TABLE ONLY public.categories_subcategory
    ADD CONSTRAINT uniq_subcategory_slug_per_category UNIQUE (category_id, slug);

CREATE INDEX accounts_us_role_2b136f_idx ON public.accounts_user USING btree (role, is_active);

CREATE INDEX accounts_user_email_b2644a56_like ON public.accounts_user USING btree (email varchar_pattern_ops);

CREATE INDEX accounts_user_groups_group_id_bd11a704 ON public.accounts_user_groups USING btree (group_id);

CREATE INDEX accounts_user_groups_user_id_52b62117 ON public.accounts_user_groups USING btree (user_id);

CREATE INDEX accounts_user_phone_c603acdd_like ON public.accounts_user USING btree (phone varchar_pattern_ops);

CREATE INDEX accounts_user_role_57e97df0 ON public.accounts_user USING btree (role);

CREATE INDEX accounts_user_role_57e97df0_like ON public.accounts_user USING btree (role varchar_pattern_ops);

CREATE INDEX accounts_user_user_permissions_permission_id_113bb443 ON public.accounts_user_user_permissions USING btree (permission_id);

CREATE INDEX accounts_user_user_permissions_user_id_e4f0a161 ON public.accounts_user_user_permissions USING btree (user_id);

CREATE INDEX advertiseme_placeme_95c965_idx ON public.advertisements_advertisement USING btree (placement, is_active);

CREATE INDEX advertiseme_start_a_e251f5_idx ON public.advertisements_advertisement USING btree (start_at, end_at);

CREATE INDEX advertisements_advertisement_placement_2813040b ON public.advertisements_advertisement USING btree (placement);

CREATE INDEX advertisements_advertisement_placement_2813040b_like ON public.advertisements_advertisement USING btree (placement varchar_pattern_ops);

CREATE INDEX ai_aianalys_article_dcfb7e_idx ON public.ai_aianalysisresult USING btree (article_id, created_at DESC);

CREATE INDEX ai_aianalysisresult_article_id_34bf2ba5 ON public.ai_aianalysisresult USING btree (article_id);

CREATE INDEX ai_aianalysisresult_requested_by_id_946f7258 ON public.ai_aianalysisresult USING btree (requested_by_id);

CREATE INDEX ai_plagiari_article_674f45_idx ON public.ai_plagiarismcheckresult USING btree (article_id, created_at DESC);

CREATE INDEX ai_plagiari_status_817e32_idx ON public.ai_plagiarismcheckresult USING btree (status);

CREATE INDEX ai_plagiarismcheckresult_article_id_fa60c6d4 ON public.ai_plagiarismcheckresult USING btree (article_id);

CREATE INDEX ai_plagiarismcheckresult_requested_by_id_4852851c ON public.ai_plagiarismcheckresult USING btree (requested_by_id);

CREATE INDEX ai_plagiarismcheckresult_scan_id_4f09baff_like ON public.ai_plagiarismcheckresult USING btree (scan_id varchar_pattern_ops);

CREATE INDEX analytics_a_article_6a14bd_idx ON public.analytics_articledailyview USING btree (article_id, date);

CREATE INDEX analytics_a_date_1881f6_idx ON public.analytics_articledailyview USING btree (date);

CREATE INDEX analytics_articledailyview_article_id_3316fff6 ON public.analytics_articledailyview USING btree (article_id);

CREATE INDEX article_search_vector_gin ON public.articles_article USING gin (search_vector);

CREATE INDEX articles_ar_assigne_35d55b_idx ON public.articles_article USING btree (assigned_reporter_id, status);

CREATE INDEX articles_ar_author__8254d9_idx ON public.articles_article USING btree (author_id, status);

CREATE INDEX articles_ar_categor_961ad7_idx ON public.articles_article USING btree (category_id, status);

CREATE INDEX articles_ar_status_0609e3_idx ON public.articles_article USING btree (status, subscribers_notified_at);

CREATE INDEX articles_ar_status_7ee05d_idx ON public.articles_article USING btree (status, access_level);

CREATE INDEX articles_ar_subcate_6fa0f5_idx ON public.articles_article USING btree (subcategory_id, status);

CREATE INDEX articles_article_access_level_e2083082 ON public.articles_article USING btree (access_level);

CREATE INDEX articles_article_access_level_e2083082_like ON public.articles_article USING btree (access_level varchar_pattern_ops);

CREATE INDEX articles_article_assigned_reporter_id_12af5887 ON public.articles_article USING btree (assigned_reporter_id);

CREATE INDEX articles_article_author_id_059aea7d ON public.articles_article USING btree (author_id);

CREATE INDEX articles_article_category_id_633dad2b ON public.articles_article USING btree (category_id);

CREATE INDEX articles_article_slug_cc61df93_like ON public.articles_article USING btree (slug varchar_pattern_ops);

CREATE INDEX articles_article_status_f68a8acd ON public.articles_article USING btree (status);

CREATE INDEX articles_article_status_f68a8acd_like ON public.articles_article USING btree (status varchar_pattern_ops);

CREATE INDEX articles_article_subcategory_id_0369b7f5 ON public.articles_article USING btree (subcategory_id);

CREATE INDEX articles_article_tags_article_id_524565b8 ON public.articles_article_tags USING btree (article_id);

CREATE INDEX articles_article_tags_tag_id_56ec02c6 ON public.articles_article_tags USING btree (tag_id);

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);

CREATE INDEX categories__categor_176815_idx ON public.categories_subcategory USING btree (category_id, is_active);

CREATE INDEX categories__is_acti_3ca3e4_idx ON public.categories_category USING btree (is_active);

CREATE INDEX categories__is_acti_ec4bb0_idx ON public.categories_industry USING btree (is_active);

CREATE INDEX categories_category_industry_id_69cc99e1 ON public.categories_category USING btree (industry_id);

CREATE INDEX categories_category_name_debcfc14_like ON public.categories_category USING btree (name varchar_pattern_ops);

CREATE INDEX categories_category_slug_6fddebb1_like ON public.categories_category USING btree (slug varchar_pattern_ops);

CREATE INDEX categories_industry_name_8ce4f89a_like ON public.categories_industry USING btree (name varchar_pattern_ops);

CREATE INDEX categories_industry_slug_5d79c9a7_like ON public.categories_industry USING btree (slug varchar_pattern_ops);

CREATE INDEX categories_subcategory_category_id_58b66954 ON public.categories_subcategory USING btree (category_id);

CREATE INDEX categories_subcategory_slug_b4319cda ON public.categories_subcategory USING btree (slug);

CREATE INDEX categories_subcategory_slug_b4319cda_like ON public.categories_subcategory USING btree (slug varchar_pattern_ops);

CREATE INDEX categories_tag_name_f3370535_like ON public.categories_tag USING btree (name varchar_pattern_ops);

CREATE INDEX categories_tag_slug_f1649e4b_like ON public.categories_tag USING btree (slug varchar_pattern_ops);

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);

CREATE INDEX media_artic_article_b53781_idx ON public.media_articleimage USING btree (article_id, is_featured);

CREATE INDEX media_articleimage_article_id_20e478bb ON public.media_articleimage USING btree (article_id);

CREATE INDEX media_articleimage_uploaded_by_id_d0046897 ON public.media_articleimage USING btree (uploaded_by_id);

CREATE INDEX media_mediametadata_checksum_6a423b4d ON public.media_mediametadata USING btree (checksum);

CREATE INDEX media_mediametadata_checksum_6a423b4d_like ON public.media_mediametadata USING btree (checksum varchar_pattern_ops);

CREATE INDEX notificatio_recipie_4e3567_idx ON public.notifications_notification USING btree (recipient_id, is_read);

CREATE INDEX notifications_notification_article_id_e271c332 ON public.notifications_notification USING btree (article_id);

CREATE INDEX notifications_notification_recipient_id_d055f3f0 ON public.notifications_notification USING btree (recipient_id);

CREATE INDEX reporters_a_article_da4396_idx ON public.reporters_articlereview USING btree (article_id, created_at);

CREATE INDEX reporters_articlereview_article_id_d295f551 ON public.reporters_articlereview USING btree (article_id);

CREATE INDEX reporters_articlereview_reviewer_id_66455cd3 ON public.reporters_articlereview USING btree (reviewer_id);

CREATE INDEX reporters_p_status_4bc6cf_idx ON public.reporters_publishingschedule USING btree (status, scheduled_for);

CREATE INDEX reporters_publishingschedule_article_id_e6a6e5b0 ON public.reporters_publishingschedule USING btree (article_id);

CREATE INDEX reporters_publishingschedule_scheduled_by_id_47c9d3d5 ON public.reporters_publishingschedule USING btree (scheduled_by_id);

CREATE INDEX reporters_publishingschedule_status_4b90b289 ON public.reporters_publishingschedule USING btree (status);

CREATE INDEX reporters_publishingschedule_status_4b90b289_like ON public.reporters_publishingschedule USING btree (status varchar_pattern_ops);

CREATE INDEX reporters_r_reporte_3a3232_idx ON public.reporters_reportercategoryassignment USING btree (reporter_id);

CREATE INDEX reporters_reportercategoryassignment_assigned_by_id_b7b63bc4 ON public.reporters_reportercategoryassignment USING btree (assigned_by_id);

CREATE INDEX reporters_reportercategoryassignment_category_id_085cd2e8 ON public.reporters_reportercategoryassignment USING btree (category_id);

CREATE INDEX reporters_reportercategoryassignment_reporter_id_bf630119 ON public.reporters_reportercategoryassignment USING btree (reporter_id);

CREATE INDEX subscriptio_status_067d55_idx ON public.subscriptions_subscription USING btree (status, expires_at);

CREATE INDEX subscriptio_user_id_2a19e8_idx ON public.subscriptions_subscription USING btree (user_id, status);

CREATE INDEX subscriptio_user_id_9c57a2_idx ON public.subscriptions_payment USING btree (user_id, status);

CREATE INDEX subscriptio_user_id_9c6a30_idx ON public.subscriptions_phoneotp USING btree (user_id, is_verified);

CREATE INDEX subscriptions_payment_razorpay_order_id_7369f92f_like ON public.subscriptions_payment USING btree (razorpay_order_id varchar_pattern_ops);

CREATE INDEX subscriptions_payment_status_8ff087ae ON public.subscriptions_payment USING btree (status);

CREATE INDEX subscriptions_payment_status_8ff087ae_like ON public.subscriptions_payment USING btree (status varchar_pattern_ops);

CREATE INDEX subscriptions_payment_subscription_id_f8df362c ON public.subscriptions_payment USING btree (subscription_id);

CREATE INDEX subscriptions_payment_user_id_d337a89a ON public.subscriptions_payment USING btree (user_id);

CREATE INDEX subscriptions_phoneotp_user_id_f34467f4 ON public.subscriptions_phoneotp USING btree (user_id);

CREATE INDEX subscriptions_subscription_expires_at_20fd1c18 ON public.subscriptions_subscription USING btree (expires_at);

CREATE INDEX subscriptions_subscription_plan_id_2c895107 ON public.subscriptions_subscription USING btree (plan_id);

CREATE INDEX subscriptions_subscription_status_bcf0b7da ON public.subscriptions_subscription USING btree (status);

CREATE INDEX subscriptions_subscription_status_bcf0b7da_like ON public.subscriptions_subscription USING btree (status varchar_pattern_ops);

CREATE INDEX subscriptions_subscription_user_id_a353e93d ON public.subscriptions_subscription USING btree (user_id);

CREATE INDEX subscriptions_subscriptionplan_slug_365039ee_like ON public.subscriptions_subscriptionplan USING btree (slug varchar_pattern_ops);

CREATE INDEX token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like ON public.token_blacklist_outstandingtoken USING btree (jti varchar_pattern_ops);

CREATE INDEX token_blacklist_outstandingtoken_user_id_83bc629a ON public.token_blacklist_outstandingtoken USING btree (user_id);
