<?php

namespace App\Enums;

enum NotificationType: string
{
    case ARTICLE_SUBMITTED = 'ARTICLE_SUBMITTED';
    case ARTICLE_RESUBMITTED = 'ARTICLE_RESUBMITTED';
    case CHANGES_REQUESTED = 'CHANGES_REQUESTED';
    case ARTICLE_REJECTED = 'ARTICLE_REJECTED';
    case ARTICLE_APPROVED = 'ARTICLE_APPROVED';
    case ARTICLE_SCHEDULED = 'ARTICLE_SCHEDULED';
    case ARTICLE_SCHEDULE_CANCELLED = 'ARTICLE_SCHEDULE_CANCELLED';
    case ARTICLE_PUBLISHED = 'ARTICLE_PUBLISHED';
    case ARTICLE_ASSIGNED_FOR_REVIEW = 'ARTICLE_ASSIGNED_FOR_REVIEW';
    case SUBSCRIPTION_ACTIVATED = 'SUBSCRIPTION_ACTIVATED';
    case PAYMENT_FAILED = 'PAYMENT_FAILED';
    case SUBSCRIPTION_EXPIRING = 'SUBSCRIPTION_EXPIRING';
    case SUBSCRIPTION_EXPIRED = 'SUBSCRIPTION_EXPIRED';
}
